name: Build APK

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install dependencies
        run: npm install

      - name: Generate Android folder
        run: npx expo prebuild --platform android --clean

      - name: 🚀 Build Release APK (Gradle)
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
          NODE_ENV: production
          BABEL_ENV: production
        run: |
          cd android
          chmod +x gradlew
          ./gradlew clean
          ./gradlew createBundleReleaseJsAndAssets assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: SelfGlow-APK
          path: android/app/build/outputs/apk/**/*.apk
          retention-days: 30
